apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-app-server-pod
  labels:
    io.kompose.service: app-server
  {{- include "helm.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
spec:
  replicas: {{ .Values.appServerPod.replicas }}
  selector:
    matchLabels:
      io.kompose.service: app-server
    {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        io.kompose.service: app-server
      {{- include "helm.selectorLabels" . | nindent 8 }}
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
    spec:
      containers:
      - command:
        - /entrypoint.sh
        - /start.sh
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ include "helm.fullname" . }}-db-auth
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: username
              name: {{ include "helm.fullname" . }}-db-auth
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: {{ include "helm.fullname" . }}-rabit-auth
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ include "helm.fullname" . }}-rabit-auth
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "helm.fullname" . }}-server-config-env
        image: {{ .Values.appServerPod.appServer.image.repository }}:{{ .Values.appServerPod.appServer.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.appServerPod.appServer.imagePullPolicy }}
        name: app-server
        ports:
        - containerPort: 8080
          name: http
        resources: {}
        volumeMounts:
        - mountPath: /app/uploads
          name: uploadfiles
      restartPolicy: Always
      volumes:
      - name: uploadfiles
        persistentVolumeClaim:
          claimName: {{ include "helm.fullname" . }}-uploadfiles-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-app-server-service
  labels:
    io.kompose.service: app-server
  {{- include "helm.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
spec:
  type: {{ .Values.appServerService.type }}
  selector:
    io.kompose.service: app-server
  {{- include "helm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.appServerService.ports | toYaml | nindent 2 -}}