apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "helm.fullname" . }}-mongo-pv
  labels:
    io.kompose.service: mongo-data
  {{- include "helm.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Mi
  hostPath:
    path: /tmp/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm.fullname" . }}-mongo-pvc
  labels:
    io.kompose.service: mongo-data
  {{- include "helm.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.mongoPvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.mongoPvc.storageClass | quote }}
  volumeName: {{ include "helm.fullname" . }}-mongo-pv