apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "helm.fullname" . }}-uploadfiles-pv
  labels:
  {{- include "helm.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Mi
  hostPath:
    path: /tmp/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm.fullname" . }}-uploadfiles-pvc
  labels:
    io.kompose.service: uploadfiles
  {{- include "helm.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.uploadfilesPvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.uploadfilesPvc.storageClass | quote }}
  volumeName: {{ include "helm.fullname" . }}-uploadfiles-pv