apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: celery-worker
  name: celery-worker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celery-worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: celery-worker
    spec:
      containers:
      - command:
        - /start-celeryworker.sh
        envFrom:
          - configMapRef:
              name: server-config-env
        env:
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: db-auth
                key: password
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-auth
                key: username
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: rabit-auth
                key: username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabit-auth
                key: password
        image: app_server:0.0.1
        imagePullPolicy: "IfNotPresent"
        name: celery-worker
        volumeMounts:
        - mountPath: /app/uploads
          name: uploadfiles
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: uploadfiles
        persistentVolumeClaim:
          claimName: uploadfiles-pvc