apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploadfiles-pv
  namespace: default
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: uploadfiles
  name: uploadfiles-pvc
  namespace: default
spec:
  volumeName: uploadfiles-pv
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

